#### 4. Create a 5x5 array with random integers between 1 and 100.

In [1]:
import numpy as np

In [2]:

arr = np.random.randint(1, 101, size=(5, 5))

print(arr)

[[ 52  65 100  15  34]
 [  1  43  82  32  19]
 [ 12  91  66  15  86]
 [ 86  35  52   8  88]
 [ 86 100  39  41  88]]
